#!/bin/bash
echo "Install bind haproxy httpd..."

wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
chmod +x jq
sudo mv jq /usr/local/bin/

install_named() {
  #Bind
  sudo dnf -y install bind bind-utils
  sudo systemctl enable named
  sudo systemctl start named
  sudo firewall-cmd --permanent --add-port=53/udp
}

install_haproxy() {
  #haproxy
  sudo dnf install haproxy -y
  sudo setsebool -P haproxy_connect_any 1
  sudo systemctl enable haproxy
  sudo systemctl start haproxy
  sudo firewall-cmd --permanent --add-port=6443/tcp
  sudo firewall-cmd --permanent --add-port=22623/tcp
  sudo firewall-cmd --permanent --add-service=http
  sudo firewall-cmd --permanent --add-service=https
}

install_httpd() {
  #HttpD
  sudo dnf install -y httpd
  sudo sed -i 's/Listen 80$/Listen 8080/' /etc/httpd/conf/httpd.conf
  sudo setsebool -P httpd_read_user_content 1
  sudo systemctl enable httpd
  sudo systemctl start httpd
  sudo firewall-cmd --permanent --add-port=8080/tcp
  sudo firewall-cmd --reload
}

INSTALLED_named=$(systemctl list-units --type=service |grep -o "named")
INSTALLED_haproxy=$(systemctl list-units --type=service |grep -o "haproxy")
INSTALLED_httpd=$(systemctl list-units --type=service |grep -o "httpd")

if [[ "$INSTALLED_named" == "named" ]]; then
  echo "Named already installed."
else
  install_named
fi

if [[ "$INSTALLED_haproxy" == "haproxy" ]]; then
  echo "HAProxy already installed."
else
  install_haproxy
fi

if [[ "$INSTALLED_httpd" == "httpd" ]]; then
  echo "HTTPD already installed."
else
  install_httpd
fi

echo "Downloading OpenShift 4.5 installer, oc client and fcos image/sig."
cd
sudo wget https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20200715.3.0/x86_64/fedora-coreos-32.20200715.3.0-metal.x86_64.raw.xz
sudo wget https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20200715.3.0/x86_64/fedora-coreos-32.20200715.3.0-metal.x86_64.raw.xz.sig
sudo mv fedora-coreos-32.20200715.3.0-metal.x86_64.raw.xz fcos.raw.xz
sudo mv fedora-coreos-32.20200715.3.0-metal.x86_64.raw.xz.sig fcos.raw.xz.sig
wget https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-07-29-070316/openshift-client-linux-4.5.0-0.okd-2020-07-29-070316.tar.gz
wget https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-07-29-070316/openshift-install-linux-4.5.0-0.okd-2020-07-29-070316.tar.gz
tar -zxvf openshift-client-linux-4.5.0-0.okd-2020-07-29-070316.tar.gz
tar -zxvf openshift-install-linux-4.5.0-0.okd-2020-07-29-070316.tar.gz
echo "Downloading libvirt library."
sudo dnf install -y libvirt
echo ""
echo "[Optional] Download newer version of oc/kubectl/openshift-install utils here --> https://github.com/openshift/okd/releases"
echo "Untar utils into home folder."
echo ""
echo "[Optional] Download latest FCOS baremetal images here --> https://getfedora.org/coreos/download?tab=metal_virtualized&stream=stable"
echo "Renamed them to fcos.raw.xz and fcos.raw.xz.sig into home folder."
echo "Update networking and ssh-key with..."
echo "sed -i '/192.168.0/10.1.24/g' * to update IP addresses"
echo "echo ~/.ssh/id_rsa.pub >> ~/okd4_files/install-config.yaml"
echo "exit sub-shell to continue..."
(bash)

sudo cp okd4_files/named.conf /etc/named.conf
sudo cp okd4_files/db* /var/named/
CONN=`nmcli co sh|grep eth|awk '{print $2}'`
sudo nmcli connection modify $CONN ipv4.dns "127.0.0.1"
#sudo nmcli con mod $CONN ipv4.dns-search okd.local
sudo nmcli con down $CONN
sudo nmcli con up $CONN
sudo systemctl restart named

sudo cp okd4_files/haproxy.cfg /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy

cd
sudo mv kubectl oc openshift-install /usr/local/bin/
rm -rf install_dir
mkdir install_dir
cp okd4_files/install-config.yaml ./install_dir
cp ./install_dir/install-config.yaml ./install_dir/install-config.yaml.bak
openshift-install create manifests --dir=install_dir/
openshift-install create ignition-configs --dir=install_dir/
sudo rm -rf /var/www/html/okd4
sudo mkdir -p /var/www/html/okd4
sudo cp -R install_dir/* /var/www/html/okd4/
sudo cp fcos.raw.xz* /var/www/html/okd4/
sudo chown -R apache: /var/www/html/
sudo chmod -R 755 /var/www/html/
curl localhost:8080/okd4/metadata.json | jq
