#!/bin/bash
sudo sed -i '/ okd4-bootstrap /s/^/#/' /etc/haproxy/haproxy.cfg
sudo systemctl reload haproxy

cd
mkdir .kube
cd .kube
curl -o config http://localhost:8080/okd4/auth/kubeconfig
cd

#CSR accept from compute nodes
wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
chmod +x jq
sudo mv jq /usr/local/bin/
oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs oc adm certificate approve

#NFS
sudo dnf install -y nfs-utils
sudo systemctl enable nfs-server rpcbind
sudo systemctl start nfs-server rpcbind
sudo mkdir -p /var/nfsshare/registry
sudo chmod -R 777 /var/nfsshare
sudo chown -R nobody:nobody /var/nfsshare

echo '/var/nfsshare 10.1.24.0/24(rw,sync,no_root_squash,no_all_squash,no_wdelay)' | sudo tee /etc/exports

sudo setsebool -P nfs_export_all_rw 1
sudo systemctl restart nfs-server
sudo firewall-cmd --permanent --zone=public --add-service mountd
sudo firewall-cmd --permanent --zone=public --add-service rpc-bind
sudo firewall-cmd --permanent --zone=public --add-service nfs
sudo firewall-cmd --reload

oc create -f okd4_files/registry_pv.yaml

cd
cd okd4_files
htpasswd -c -B -b users.htpasswd admin password
oc create secret generic htpass-secret --from-file=htpasswd=users.htpasswd -n openshift-config
oc apply -f htpasswd_provider.yaml

echo "Update registry with PV:"
echo "oc edit configs.imageregistry.operator.openshift.io"
echo ""
echo "managementState: Managed"
echo "storage:"
echo "    pvc:"
echo "      claim:"
      
